language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t nikmasdev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikmasdev/docker-react npm run test